# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ppa'
        packages:
          - libmlpack-dev=3.0.4-1 -V
