# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    addons:
      apt:
        sources:
          - sourceline: 'https://launchpad.net/ubuntu/focal/+source/mlpack'
        packages:
          - libmlpack-dev
          - libarmadillo-dev
          - libboost-program-options-dev
          - libboost-serialization-dev
          - libboost-test-dev
